'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Login
    
    '''<summary>
    '''claveClienteLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents claveClienteLog As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''errorClaveCli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorClaveCli As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''claveUsuarioLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents claveUsuarioLog As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''errorClaveUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorClaveUs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''contraseniaLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contraseniaLog As Global.System.Web.UI.HtmlControls.HtmlInputPassword
    
    '''<summary>
    '''pwdUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pwdUs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''errores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errores As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
