'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registro
    
    '''<summary>
    '''nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombre As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''correo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents correo As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''celular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents celular As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''fechaNac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fechaNac As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''genero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents genero As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''contrasenia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contrasenia As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''contraseniaR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contraseniaR As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''pregunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pregunta As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''respuestaPreg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents respuestaPreg As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''RegistraUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegistraUs As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
End Class
